### ISSUE TITLE
Migrate from Disqus

### ISSUE THREAD

**Issue by VincentTam** [nikoheikkila/nikoheikkila.fi#118]
Hi, this is the maintainer of @staticmanlab, a public GitLab instance of [Staicman](https://staticman.net/).  #107 has added Disqus support.  However, please revert it due to some shortcomings of some common third-party commenting systems.

1. Gitment, Gitalk and Utterance support only GitHub, and they require user login before commenting. This can scare away many non programmers from leaving a comment to your posts. Besides, comments are part of the site's static content, not a software package problem. As a result, using GtiHub issues for comment storage is wrong in principle and bad in terms of SEO.
2. Commento is not free as in free beer.  For a personal blog with small traffic, you might find a monthly fee of $5 too expensive.
3. Disqus and Isso contain a 3rd-party script to be loaded during page rendering. The code block for loading each of them shows that the static comments are not rendered as static HTML code. This hinders search engines from grabbing the comments, which are part of the site's content.  As a result, that leads to suboptimal SEO.

To see more reasons for migrating from Disqus, you may view

1. https://victorzhou.com/blog/replacing-disqus/
1. https://old.reddit.com/r/programming/comments/b9022a/switching_off_of_disqus_reduced_my_page_weight_by/
1. https://medium.com/remys-blog/ejecting-disqus-4120e9985823

You may avoid these problems by switching to Staticman, which makes use of GitHub/GitLab Pull/Merge Requests instead of issues. Under Staticman's model, static comments are YML/JSON files stored in the remote GitHub/GitLab repo (usually under data/comments, configurable through the path parameter in root-level staticman.yml), and through a static blog generator (Jekyll/Hugo/etc), the stored data are rendered as part of the content. This gives a total ownership of a static site's comments.

:information_source: There're many ways to Rome, say JAM Stack, Jekyll AWS comments, etc.

**Comment by nikoheikkila** [comment]
Thanks for raising your concern. However, I don't like the idea of storing user comments in my repository. At minimum, each post should then have an explicit confirmation box requiring users to agree their data is owned fully by me.

Disqus has a slight performance impact but for example Google Analytics has worse. Seeing how widely used platform Disqus is and being able to inject both the discussion area and comments count as simple React components makes the tradeoff acceptable. The Lighthouse score for SEO is still at 100 so there's no reason to worry about it either.
