### ISSUE TITLE
Add GitHub Actions as CI Pipeline

### ISSUE THREAD

**Issue by nikoheikkila** [nikoheikkila/nikoheikkila.fi#119]
## Description

I'd like to try out [GitHub Actions](https://github.com/features/actions) as a replacement for Travis CI. Migration should not introduce new features to the CI process or make it worse.

Pipeline definition file in YAML should be placed under the `.github/` directory in the project.

## Acceptance Criteria

- Runs in Actions won't take longer than in Travis (this is debatable, but let's keep the pipeline duration under 10 minutes)
- Following steps are run on each push:
  - Code linting (`yarn lint`)
  - Unit tests (`yarn test:dev`)
  - Integration tests (`yarn test:e2e`)
  - Accessibility tests (`yarn test:a11y`)
- **Bonus:** Tests are run in parallel if possible

**Comment by LOLdevelopr** [comment]
I would like to take this 👍

**Comment by nikoheikkila** [comment]
@LOLdevelopr You're welcome, and ask if you need any help.
